language: php

addons:
  apt:
    packages: &common_pkg
      - libgpgme11-dev
      - gnupg2

services:
  - memcached

matrix:
  include:

#    # PHP 5.5 / MYSQL 5.5
#    - php: 5.5
#      env: DB=mysql MYSQL_VERSION=5.5
#      dist: trusty
#      sudo: required
#      addons: &php5_addon
#        apt:
#          packages:
#            - *common_pkg
#            - php5-memcached
#            - php5-common
#            - php5-curl
#            - php5-mcrypt
#            - php5-mysql
#      # Mysql 5.5 requires extra operations to be installed.
#      before_install: &before_install_mysql55
#        - sudo service mysql stop
#        - sudo rm -fr /var/lib/mysql
#        - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5
#        - sudo service mysql restart
#
#    # PHP 5.5 / MYSQL 5.6
#    - php: 5.5
#      env: DB=mysql MYSQL_VERSION=5.6
#      dist: trusty
#      sudo: required
#      addons: *php5_addon
#
#    # PHP 5.6 / MYSQL 5.5
#    - php: 5.6
#      env: DB=mysql MYSQL_VERSION=5.5
#      dist: trusty
#      sudo: required
#      addons: *php5_addon
#      before_install: *before_install_mysql55
#
#    # PHP 5.6 / MYSQL 5.6
#    - php: 5.6
#      env: DB=mysql MYSQL_VERSION=5.6
#      dist: trusty
#      sudo: required
#      addons: *php5_addon
#
#    # PHP 5.6 / MYSQL 5.7
#    - php: 5.6
#      env: DB=mysql MYSQL_VERSION=5.7
#      dist: trusty
#      sudo: required
#      addons: *php5_addon
#      # Mysql 5.7 requires extra operations to be installed.
#      before_install: &before_install_mysql57
#        - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
#        - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
#        - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
#        - sudo apt-get update -q
#        - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
#        - sudo mysql_upgrade

    # PHP 7 / MYSQL 5.6
    - php: 7.0
      env: DB=mysql MYSQL_VERSION=5.6
      dist: trusty
      sudo: required

#    # PHP 7.1 / MYSQL 5.6
#    - php: 7.1
#      env: DB=mysql MYSQL_VERSION=5.6
#      dist: trusty
#      sudo: required
#      addons: *php7_addon
#
#    # HHVM / MYSQL 5.6
#    - php: hhvm
#      env: DB=mysql MYSQL_VERSION=5.6
#      dist: trusty
#      sudo: required
#      addons: &hhvm_addon
#        apt:
#          packages:
#            - *common_pkg

  allow_failures:
    - php: 5.6
      env: DB=mysql MYSQL_VERSION=5.7
    - php: 7.0
      env: DB=mysql MYSQL_VERSION=5.6
    - php: 7.1
      env: DB=mysql MYSQL_VERSION=5.6
    - php: hhvm
      env: DB=mysql MYSQL_VERSION=5.6

before_script:
  - sh .travis_before_script.sh

script:
  - mkdir -p build/logs
  - app/Console/cake test app All --stderr --configuration=app/Test/phpunit.xml

after_script:
  - php Vendor/bin/coveralls -v

notifications:
  email: false
